// models/ticket.dart

import 'package:cloud_firestore/cloud_firestore.dart';

class Ticket {
  String id; // Unique ID for the ticket (generated by Firebase)
  String title; // Title or subject of the request
  String description; // Detailed description of the issue/request
  String imageUrl; // URL of the uploaded image related to the request
  String department; // The department the request is coming from
  String userId; // ID of the user who created the ticket
  String
      status; // Status of the request (e.g., "Pending", "Approved", "In Progress", "Completed")
  Timestamp createdAt; // Time the request was created
  Timestamp updatedAt; // Time the request was last updated

  Ticket({
    required this.id,
    required this.title,
    required this.description,
    required this.imageUrl,
    required this.department,
    required this.userId,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
  });

  // Factory constructor to create a Ticket object from a Firestore document
  factory Ticket.fromDocument(DocumentSnapshot doc) {
    Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
    return Ticket(
      id: doc.id,
      title: data['title'] ?? '',
      description: data['description'] ?? '',
      imageUrl: data['imageUrl'] ?? '',
      department: data['department'] ?? '',
      userId: data['userId'] ?? '',
      status: data['status'] ?? 'Pending',
      createdAt: data['createdAt'] ?? Timestamp.now(),
      updatedAt: data['updatedAt'] ?? Timestamp.now(),
    );
  }

  // Method to convert Ticket object to a Firestore-compatible map
  Map<String, dynamic> toMap() {
    return {
      'title': title,
      'description': description,
      'imageUrl': imageUrl,
      'department': department,
      'userId': userId,
      'status': status,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
    };
  }
}
